// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// insertMinReqRem
NumericMatrix insertMinReqRem(IntegerVector anHs, IntegerVector anHt);
RcppExport SEXP satellite_insertMinReqRem(SEXP anHsSEXP, SEXP anHtSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type anHs(anHsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type anHt(anHtSEXP);
    __result = Rcpp::wrap(insertMinReqRem(anHs, anHt));
    return __result;
END_RCPP
}
